# Generated by Django 2.2.13 on 2020-09-17 02:03

import course.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='本名')),
                ('length', models.IntegerField(verbose_name='身高')),
                ('sex', models.CharField(max_length=2, verbose_name='性别')),
                ('detail', models.TextField(verbose_name='用户简介')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('img', models.ImageField(upload_to='user', verbose_name='头像')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '个人简介',
                'verbose_name_plural': '个人简介',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('img', models.ImageField(blank=True, null=True, upload_to=course.models.article_img_path, verbose_name='文章配图')),
                ('content', markdownx.models.MarkdownxField(verbose_name='内容')),
                ('abstract', markdownx.models.MarkdownxField(max_length=255, null=True, verbose_name='摘要')),
                ('visited', models.PositiveIntegerField(default=0, verbose_name='访问量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ManyToManyField(to='course.Category', verbose_name='文章分类')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '文章内容',
                'verbose_name_plural': '文章内容',
                'ordering': ['-created_at'],
            },
        ),
    ]
